### ISSUE TITLE
[ENHANCEMENT] wsl2에 Navix cloud image 지원

### ISSUE THREAD

**Issue by ChaeHanbaek** [NaverCloudPlatform/Navix#10]
### Please describe your question.

Navix-Container-Base-9.5-20241129.0.x86_64.tar.xz를 받아서 RockyLinux9설치방법을 참조하여 설치해도 실행하면 에러가 나는데 혹시 해결방법이 있을까요?

**Comment by ChaeHanbaek** [comment]
PS C:\Users\user> wsl -d Navix9
<3>WSL (10) ERROR: CreateProcessParseCommon:763: Failed to translate C:\Users\user
<3>WSL (10) ERROR: CreateProcessParseCommon:809: getpwuid(0) failed 2
<3>WSL (10) ERROR: UtilTranslatePathList:2852: Failed to translate C:\WINDOWS\system32
<3>WSL (10) ERROR: UtilTranslatePathList:2852: Failed to translate C:\WINDOWS
<3>WSL (10) ERROR: UtilTranslatePathList:2852: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (10) ERROR: UtilTranslatePathList:2852: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (10) ERROR: UtilTranslatePathList:2852: Failed to translate C:\WINDOWS\System32\OpenSSH\
~
에러메시지는 위와 같습니다.

**Comment by songhee1030** [comment]
@ChaeHanbaek 님 안녕하세요, 
제보해주셔서 감사합니다.

현재 wsl 에서도 사용가능하도록 이미지 제작 중에 있습니다.
테스트 완료 후 공유 드리겠습니다 :)

**Comment by ChaeHanbaek** [comment]
감사합니다.

**Comment by songhee1030** [comment]
@ChaeHanbaek 님,

WSL용 이미지로 [Navix-Container-WSL](https://dlnavix.navercorp.com/cloud-images/Navix-Container-WSL-latest.x86_64.tar.xz) 추가해뒀습니다.
위에 사용하신 Navix-Container-Base 이미지는 컨테이너(도커)용으로 WSL에서는 동작하지 않습니다. 

감사합니다 :)

**Comment by ChaeHanbaek** [comment]
wsl 정상적으로 설치되고 실행되는 것 확인하였습니다. 고생 많으셨습니다. 
감사합니다.
