### ISSUE TITLE
[BUG] Firefox에서 사이트 방문이 안됩니다.

### ISSUE THREAD

**Issue by blackcon** [NaverCloudPlatform/Navix#12]
### Component

Firefox (기본 내장된 소프트웨어)

### Describe the bug

- Firefox에서 인터넷을 연결할 때 `NS_ERROR_SOCKET_CREATE_FAILED`에러 발생 (이미지 참고)
- 단, wget, curl, ping 등 터미널에서 사용하는 도구들은 대상 사이트에서 response를 잘 받아옴

### Screenshots / Live demo link
**Firefox 사용 화면**
    <img width="1019" alt="image" src="https://github.com/user-attachments/assets/ee84a19a-5c0d-4687-bdb5-35a64dd2c3a9">
**기타 네트워크 도구 사용 화면**
    <img width="1014" alt="image" src="https://github.com/user-attachments/assets/7149d855-4cd6-44c4-a7bf-edd5bce45672">

_No response_

### Environment

* OS: Navix 9.5
* VM: Hyper-V
* Host: Windows 10

**Comment by leejun9503** [comment]
안녕하세요.
확인 결과 실제로 문제가 발생하였고, OS에서 기본 제공하는 파이어폭스의 버전의 문제로 확인했습니다.
불편하시겠지만 9.4 업데이트 [레포지토리](https://dlnavix.navercorp.com/9.4/x86_64/Updates/os/)에서 제공되는 파이어폭스의 구버전으로 다운그레이드하시면 웹페이지에 정상적으로 액세스 가능합니다.
또한 현재 문제가 발생한 파이어폭스의 경우 업데이트가 이미 나와있어 빠르게 빌드하고 업데이트 레포지토리로 제공드릴수 있도록 하겠습니다.
패키지 업데이트 뒤 알려드리겠습니다.

**Comment by forreset06** [comment]
저는 아예 나오지도 않았어요... 아예 아무것도 안뜨더라고요... 개인적으로 쓰려고 한건데..
그래서 epel 패키지 추가해서 chromium을 설치했습니다.. 정상적으로 잘 뜨더라고요.. 하지만 chrome을 써야해서 chrome을 설치했죠 아주 잘됩니다.

**Comment by leejun9503** [comment]
안녕하세요.
12월 12일자로 문제가 수정된 firefox가 9.5 업데이트 레포지토리로 배포되었습니다.
https://dlnavix.navercorp.com/9.5/x86_64/Updates/os/Packages/firefox-128.3.0-1.1.el9_4.x86_64.rpm

**Comment by blackcon** [comment]
@leejun9503 안녕하세요.
빠른 배포 감사드립니다 :) 덕분에 인터넷을 할 수 있게 되었어요!
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/9c594f5f-18bf-4a02-b3e8-0011a9da9d34" />
