### ISSUE TITLE
[ENHANCEMENT] Download Page Update 부탁드립니다.

### ISSUE THREAD

**Issue by SeungYeop-Yang** [NaverCloudPlatform/Navix#15]
### Is your feature request related to a problem? Please describe.

제 [LinkedIn post](https://www.linkedin.com/posts/seung-yeop-yang_%EB%84%A4%EC%9D%B4%EB%B2%84%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C%EA%B0%80-%EC%9E%90%EC%B2%B4-%EA%B0%9C%EB%B0%9C%ED%95%9C-%EB%A6%AC%EB%88%85%EC%8A%A4-navix-%EC%B6%9C%EC%8B%9C-activity-7273724286819819520-Gy0C?utm_source=share&utm_medium=member_desktop) 참조 하시고요.

몇 가지 건의 드립니다.
1. CHECKSUM 파일 링크 instead of CHECKSUM value
2. cloud image 없는 데, 빌드 되는 데로 링크 해주시면 감사하겠습니다.
3. Naver Cloud Container Registry가 없나요? 없으면 ghcr이나 docker hub에 올려주시면 좋겠습니다.

RockyLinux [Download 페이지](https://rockylinux.org/download) 비슷하게 만들어주시면 좋겠습니다.

### Describe the solution you'd like

1. CHECKSUM 파일 링크 instead of CHECKSUM value
2. cloud image 없는 데, 빌드 되는 데로 링크 해주시면 감사하겠습니다.
3. Naver Cloud Container Registry가 없나요? 없으면 ghcr이나 docker hub에 올려주시면 좋겠습니다.

### Describe alternatives you've considered

RockyLinux [Download 페이지](https://rockylinux.org/download) 비슷하게 만들어주시면 좋겠습니다.

**Comment by NAVIXsup1** [comment]
제안 감사합니다.
다음 업데이트때 반영할 수 있는것들은 반영하겠습니다.
