### ISSUE TITLE
[Q] Bottles(Wine frontend) collides with SELinux

### ISSUE THREAD

**Issue by hansolj** [NaverCloudPlatform/Navix#16]
### Component

Wine의 프론트엔드인 Bottles를 Flatpak을 통해 설치한 후, 새로운 bottle(컨테이너에 해당)을 형성하는 과정에서 SELinux와 다수의 충돌이 보고되었습니다.

### Describe the bug

SELinux는 /home/sol/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/bin/wine64-preloader execmod에서 파일가 /home/sol/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/lib/wine/x86_64-windows/ntdll.dll 액세스하지 못하게 합니다.

*****  플러그인 allow_execmod (53.1 confidence) 제안   *****************************

If this issue occurred during normal system operation.
그 다음에 this alert could be a serious issue and your system could be compromised. Setroubleshoot examined '/home/sol/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/lib/wine/x86_64-windows/ntdll.dll' to make sure it was built correctly, but can not determine if this application has been compromised.
Do
contact your security administrator and report this issue

*****  플러그인 catchall_boolean (42.6 confidence) 제안   **************************

네가 원한다면 selinuxuser에서 execmod로 허용
그 다음에 'selinuxuser_execmod' 부울을 활성화하여 이에 대해 SELinux에 알려야 합니다.

Do
setsebool -P selinuxuser_execmod 1

*****  플러그인 catchall (5.76 confidence) 제안   **********************************

네가 그렇게 생각하면 wine64-preloader가 허용되어야합니다. execmod 에 대한 액세스 ntdll.dll file 기본적으로.
그 다음에 이 결점를 보고해야 합니다.
이러한 접근를 허용하기 위해 로컬 정채 모듈을 생성할 수 있습니다.
Do
다음을 실행하여 현재상태의 이 접근을 허용하세요:
# ausearch -c 'wineboot.exe- - | audit2allow -M my-winebootexe
# semodule -X 300 -i my-winebootexe.pp

추가 정보:
소스 문맥                         unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1
                              023
대상 문맥                         unconfined_u:object_r:user_home_t:s0
대상 객체                         /home/sol/.var/app/com.usebottles.bottles/data/bot
                              tles/runners/soda-9.0-1/lib/wine/x86_64-windows/nt
                              dll.dll [ file ]
원천                            wineboot.exe
원천 경로                         /home/sol/.var/app/com.usebottles.bottles/data/bot
                              tles/runners/soda-9.0-1/bin/wine64-preloader
포트                            <알려지지 않음>
호스트                           localhost.localdomain
원천 RPM 꾸러미                    
대상 RPM 꾸러미(package)           
SELinux 정책 RPM                selinux-policy-targeted-38.1.45-3.el9_5.noarch
로컬 정책 RPM                     selinux-policy-targeted-38.1.45-3.el9_5.noarch
Selinux 활성화                   True
정책 유형                         targeted
강제 모드                         Enforcing
호스트명                          localhost.localdomain
기술환경                          Linux localhost.localdomain
                              5.14.0-503.15.1.el9_5.x86_64 #1 SMP
                              PREEMPT_DYNAMIC Fri Nov 29 13:39:51 KST 2024
                              x86_64 x86_64
통지 카운트                        48
초기 화면                         2024-12-16 19:36:02 KST
마지막 화면                        2024-12-16 19:38:34 KST
로컬 ID                         7b07f695-83e5-45bb-9da3-f4ac454efd0c

원 감사 메세지
type=AVC msg=audit(1734345514.459:224): avc:  denied  { execmod } for  pid=5726 comm="start.exe" path="/home/sol/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/lib/wine/x86_64-windows/ntdll.dll" dev="dm-2" ino=67306117 scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0

type=SYSCALL msg=audit(1734345514.459:224): arch=x86_64 syscall=mprotect success=no exit=EACCES a0=6ffffff41000 a1=6f000 a2=5 a3=6ffe8ff4 items=0 ppid=4093 pid=5726 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=3 comm=start.exe exe=/home/sol/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/bin/wine64-preloader subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)

Hash: wineboot.exe,unconfined_t,user_home_t,file,execmod

### Expected behavior

Bottles는 정상적으로 생성되었으나 실행될지 불확실합니다.

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/c80b14ad-3c2e-4afa-8124-206be86efd63)

### Environment

os : navix

**Comment by NaverLinux** [comment]
안녕하세요.
gnome 데스크탑에서 제공되는 flatpak이라는 어플리케이션 샌드박스를 통해 Bottles라는 wine wrapper를 설치 뒤 실행하려고 했지만 문제가 발생했다는 질문으로 이해했습니다.
해당 프로그램의 경우 서드 파티 프로그램이기 때문에, 저희가 지원해드릴수 있는 범위를 벗어나는 케이스입니다.
저희 Navix 레포지토리는 Navix에 내장된 구성요소의 버그나 개선 사항을 처리해드릴수 있지만, 서드 파티 프로그램에 대해서 지원드리기 어려운점 다시 한번 말씀드립니다.
타 Enterprise Linux 배포판의 케이스를 참조해보시거나, Bottles의 공식 문서를 참조하여 문제를 해결해보시는것을 제안드립니다.
