### ISSUE TITLE
[Q] 오타 수정 요청

### ISSUE THREAD

**Issue by PiCoPress** [NaverCloudPlatform/Navix#7]
### Please describe you question.

![1733721217964](https://github.com/user-attachments/assets/52658df1-d9cc-4265-8638-2b3f886197ef)
무었 -> 무엇으로 정정 요청해요

**Comment by NaverLinux** [comment]
@PiCoPress 님 안녕하세요,  
정정 했습니다. 
제보해주셔서 감사합니다 :)
