### ISSUE TITLE
[Q] 코드 제공 요청

### ISSUE THREAD

**Issue by minuuu0** [NaverCloudPlatform/Navix#9]
### 코드 제공 요청 (Request for Source Code)

안녕하세요, `navix` 운영체제에 대한 소스코드를 요청드립니다.

현재는 배포판과 관련된 패키지 파일들만 포함되어 있으며, 운영체제의 소스코드가 포함되어 있지 않은 것 같습니다. 이에 따라, 아래와 같은 사항에 대해 도움을 요청드립니다:

1. **소스코드 제공 여부 확인**:
   - `navix` 운영체제의 소스코드는 공개되어 있나요? 공개되어 있다면 해당 소스코드를 받을 수 있는 방법을 알려주시면 감사하겠습니다.

2. **관련된 추가 정보**:
   - 추후에 코드 제공 예정이라면 대략적인 날짜 등 추가 정보 공유 요청드립니다.

이와 관련하여 자세한 정보를 제공해 주시면 감사하겠습니다. 
감사합니다.

**Comment by NaverLinux** [comment]
@Tiel0043 님 안녕하세요, 

네, 소스 코드  [Navix repository](https://dlnavix.navercorp.com/navix/) 에 공개되어 있습니다.  아래 링크와 같이 원하시는 레파지토리(BaseOS, AppStream, CRB ..) 에 접근해서 확인 가능합니다 :)
`https://dlnavix.navercorp.com/navix/9/x86_64/{레파지토리}/source/tree/`

소스 ISO 도 공개되어 있으니 참고 부탁드립니다. [SourceISO](https://dlnavix.navercorp.com/navix/9/x86_64/BaseOS/source/iso/)

**Comment by minuuu0** [comment]
리눅스 패키지 형식을 잘 몰라서 소스 파일인지 모르고 넘어갔네요!
친절한 설명 감사합니다
좋은 하루 보내세요 :)
